spring.application.name=ms-bff
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/bdda1d7c-134f-4a96-a337-c592e586a963/
spring.security.oauth2.resourceserver.jwt.audiences=api://4ea351c0-ef77-41aa-acac-dd63f5d0648f
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

orders.service.url=http://localhost:8081