spring.application.name=ms-bff
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/01284d2f-c1ab-4cc2-9ac4-39af0872bf42/

spring.security.oauth2.resourceserver.jwt.audiences=api://5c786dab-1811-4357-aba9-63a6e2485924

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration